=== daedmen/Serialized/examples/serialized.dtd
<!--

    Serialized - PHP Library for Serialized Data

    Copyright (C) 2010-2011 Tom Klingenberg, some rights reserved

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program in a file called COPYING. If not, see
    <http://www.gnu.org/licenses/> and please report back to the original
    author.

 	============

    This is Serialized DTD.

    Serialized includes the superset of PHP serialized
    types and their values.

        Draft: 0.2.0 alpha

        Authors:
            Tom Klingenberg
            Patrick C. Engel

     Further information about Serialized is available at:

         https://github.com/ktomk/Serialized

-->

<!--====== datatypes ======-->

<!ENTITY % type.simple " null | bool | int | float | string " >
<!ENTITY % type.complex " array | object " >
<!ENTITY % type.base " %type.simple; | %type.complex; " >
<!ENTITY % type.recursion " recursion | recursionref " >
<!ENTITY % type.all " %type.simple; | %type.complex; | %type.recursion; " >

<!--====== named values ======-->

<!ENTITY % Int "CDATA" >
	<!-- an integer value -->

<!ENTITY % AbsInt "%Int;" >
	<!-- a positive integer value or 0 -->

<!ENTITY % PositiveInt "%Int;" >
	<!-- a positive integer value greater 0 -->

<!ENTITY % Count "%AbsInt;" >
	<!-- Count, 0 or positive integer -->

<!ENTITY % Bool "(true|false)" >
	<!-- a boolean value -->

<!ENTITY % Float "CDATA" >
	<!-- a float value -->

<!ENTITY % Strlen "%AbsInt;" >
	<!-- Length of a string, 0 or positive integer -->

<!ENTITY % Ref "%PositiveInt;" >
	<!-- Reference index of/to an existing element, a positive integer -->

<!ENTITY % KeyType "(string|int)" >
	<!-- Array keys can be either string or integer  -->

<!ENTITY % PropAccess "(public|protected|private)" >
	<!-- Property Access can either be public, protected or private -->

<!--====== root ======-->

<!ELEMENT serialized ( variables|%type.base; )>

<!--====== simple/simple ======-->

<!ELEMENT null EMPTY >

<!ELEMENT bool EMPTY >
<!ATTLIST bool
  value %Bool; #REQUIRED
  >

<!ELEMENT int EMPTY >
<!ATTLIST int
  value %Int; #REQUIRED
  >

<!ELEMENT float EMPTY >
<!ATTLIST float
  value %Float; #REQUIRED
  >

<!ELEMENT string EMPTY >
<!ATTLIST string
  len   %Strlen; #REQUIRED
  value CDATA    #REQUIRED
  >

<!--====== compound ======-->

<!ELEMENT array ( item* ) >
<!ATTLIST array
  members %Count; #REQUIRED
  >

<!ELEMENT item ( %type.all; ) >
<!ATTLIST item
  name CDATA     #REQUIRED
  type %KeyType; #REQUIRED
  >

<!ELEMENT object ( property* ) >
<!ATTLIST object
  class   CDATA   #REQUIRED
  members NMTOKEN #REQUIRED
  >

<!ELEMENT property ( %type.all; ) >
<!ATTLIST property
  class  CDATA        #IMPLIED
  access %PropAccess; "public"
  name   CDATA        #REQUIRED
  >

<!--====== recursion ======-->

<!ELEMENT recursion EMPTY >
<!ATTLIST recursion
  value %Ref; #REQUIRED
  >

<!ELEMENT recursionref EMPTY >
<!ATTLIST recursionref
  value %Ref; #REQUIRED
  >

<!--====== session ======-->

<!ELEMENT variables ( var* ) >
<!ATTLIST variables
  count %Count; #IMPLIED
  >

<!ELEMENT var ( %type.base; )  >
<!ATTLIST var
  name CDATA #REQUIRED
  >

=== daedmen/Serialized/examples/serialized.xml
<?xml version="1.0"?>
<!--

    Serialized - PHP Library for Serialized Data
     
    Copyright (C) 2010-2011 Tom Klingenberg, some rights reserved
     
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.
     
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.
     
    You should have received a copy of the GNU Affero General Public License
    along with this program in a file called COPYING. If not, see
    <http://www.gnu.org/licenses/> and please report back to the original
    author.
    
 	============

    This is a XML dump of a more complex serialized array created
    with Serialized and the XML Dumper.
    
    See serialized.dtd
    
-->
<!DOCTYPE serialized SYSTEM "serialized.dtd">
<serialized>
  <array members="3">
    <item name="0" type="int">
      <array members="4">
        <item name="user" type="string">
          <string len="9" value="user-name"/>
        </item>
        <item name="network" type="string">
          <array members="1">
            <item name="localip" type="string">
              <string len="7" value="1.2.3.4"/>
            </item>
          </array>
        </item>
        <item name="2" type="int">
          <string len="4" value="Zwei"/>
        </item>
        <item name="language" type="string">
          <string len="6" value="german"/>
        </item>
      </array>
    </item>
    <item name="1" type="int">
      <object class="stdClass" members="6">
        <property name="property" access="public">
          <string len="4" value="test"/>
        </property>
        <property name="float" access="public">
          <float value="1"/>
        </property>
        <property name="bool" access="public">
          <bool value="true"/>
        </property>
        <property name="null" access="public">
          <null/>
        </property>
        <property name="recursion" access="public">
          <recursion value="8"/>
        </property>
        <property name="recursionref" access="public">
          <recursion value="8"/>
        </property>
      </object>
    </item>
    <item name="2" type="int">
      <object class="Serialized\Dumper\testObjectChild" members="6">
        <property class="Serialized\Dumper\testObjectChild" name="ca" access="private">
          <string len="7" value="private"/>
        </property>
        <property name="cb" access="protected">
          <string len="9" value="protected"/>
        </property>
        <property name="cc" access="public">
          <string len="6" value="public"/>
        </property>
        <property class="Serialized\Dumper\testObjectParent" name="pa" access="private">
          <string len="15" value="private, parent"/>
        </property>
        <property name="pb" access="protected">
          <string len="17" value="protected, parent"/>
        </property>
        <property name="pc" access="public">
          <string len="14" value="public, parent"/>
        </property>
      </object>
    </item>
  </array>
</serialized>

=== daedmen/Serialized/examples/session.xml
<?xml version="1.0"?>
<!--

    Serialized - PHP Library for Serialized Data

    Copyright (C) 2010-2011 Tom Klingenberg, some rights reserved

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program in a file called COPYING. If not, see
    <http://www.gnu.org/licenses/> and please report back to the original
    author.

 	============

    This is a XML dump of a more complex serialized array created
    with Serialized and the XML Dumper.

    See serialized.dtd

-->
<!DOCTYPE serialized SYSTEM "serialized.dtd">
<serialized>
  <variables count="3">
    <var name="test">
      <int value="1"/>
    </var>
    <var name="more">
      <array members="2">
        <item name="0" type="int">
          <int value="56"/>
        </item>
        <item name="key" type="string">
          <int value="57"/>
        </item>
      </array>
    </var>
    <var name="again">
      <int value="2"/>
    </var>
  </variables>
</serialized>
